name: Copy Files to Bin

on:
  push:
    branches:
      - main

jobs:
  copy_files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Create Bin Directory
        run: mkdir -p bin/

      - name: Copy CLI, GUI and KO to Bin
        run: |
          cp -f cli/bin/VersaGuard-cli bin/
          cp -f gui/bin/VersaGuard-gui bin/
          cp -f core/bin/VersaGuard_core.ko bin/
          
      - name: Commit & Push
        uses: action-x/commit@v2.9
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          push-branch: 'main'
          force-push: 'true'
          commit-message: 'Update bin directory'
          name: github-actions[bot]
          email: github-actions[bot]@noreply.github.com
